### ISSUE TITLE
Create on-boarding exercise

### ISSUE THREAD

**Issue by rbwatson** [rbwatson/GoBabyGo#2]
Provide an exercise in which new writers and contributors will:

1. create a new topic
2. test it on their local repo
3. Submit a pull request
4. Sync their fork with the master/origin repo

**Comment by EvanBG42** [comment]
The current readme covers some of this, but does not provide an exercise. In order to make on-boarding smoother, here's what I propose:

 - Build a series of onboarding pages
    * How to contribute
    * Documentation and Development Tools
    * Making Contributions 
    * Page Layouts (could be merged with contributions?)
    * Issues
    * Walkthrough Exercise

- Leave the following in the README
    * Document intro
    * Repo Organization
    * GBG Info

Please let me know what you think. I think each of the onboarding pages could be separate issues.
